export const BEAT_VALUES = [
  { value: 1 / 64, label: "1/64" },
  { value: (1 / 32) * (2 / 3), label: "1/32t" },
  { value: 1 / 32, label: "1/32" },
  { value: (1 / 32) * 1.5, label: "1/32d" },
  { value: 1 / 24, label: "1/16t" },
  { value: 1 / 16, label: "1/16" },
  { value: (1 / 16) * 1.5, label: "1/16d" },
  { value: 1 / 12, label: "1/8t" },
  { value: 1 / 8, label: "1/8" },
  { value: (1 / 8) * 1.5, label: "1/8d" },
  { value: 1 / 6, label: "1/4t" },
  { value: 1 / 4, label: "1/4" },
  { value: (1 / 4) * 1.5, label: "1/4d" },
  { value: 1 / 3, label: "1/2t" },
  { value: 1 / 2, label: "1/2" },
  { value: (1 / 2) * 1.5, label: "1/2d" },
  { value: 2 / 3, label: "1t" },
  { value: 1, label: "1" },
  { value: 1.5, label: "1d" },
  { value: 2, label: "2" },
  { value: 3, label: "3" },
  { value: 4, label: "4" },
  { value: 6, label: "6" },
  { value: 8, label: "8" },
  { value: 12, label: "12" },
  { value: 16, label: "16" },
  { value: 24, label: "24" },
  { value: 32, label: "32" },
].sort((a, b) => a.value - b.value);

export const PITCH_VALUES = [
  { value: 1 / 8, label: "1/8" },
  { value: 1 / 4, label: "1/4" },
  { value: 1 / 2, label: "1/2" },
  { value: 1, label: "1" },
  { value: 2, label: "2" },
  { value: 3, label: "3" },
  { value: 4, label: "4" },
  { value: 5, label: "5" },
  { value: 6, label: "6" },
  { value: 7, label: "7" },
  { value: 8, label: "8" },
  { value: 9, label: "9" },
  { value: 10, label: "10" },
  { value: 11, label: "11" },
  { value: 12, label: "12" },
  { value: 18, label: "18" },
  { value: 24, label: "24" },
  { value: 36, label: "36" },
  { value: 48, label: "48" },
  { value: 60, label: "60" },
  { value: 72, label: "72" },
  { value: 84, label: "84" },
  { value: 96, label: "96" },
];

export const MULTIPLIER_VALUES = [
  { value: 1 / 128, label: "x 1/128" },
  { value: 1 / 64, label: "x 1/64" },
  { value: 1 / 32, label: "x 1/32" },
  { value: 1 / 16, label: "x 1/16" },
  { value: 1 / 8, label: "x 1/8" },
  { value: 1 / 4, label: "x 1/4" },
  { value: 1 / 3, label: "x 1/3" },
  { value: 1 / 2, label: "x 1/2" },
  { value: 2 / 3, label: "x 2/3" },
  { value: 3 / 4, label: "x 3/4" },
  { value: 1, label: "x 1" },
  { value: 1.5, label: "x 1.5" },
  { value: 2, label: "x 2" },
  { value: 3, label: "x 3" },
  { value: 4, label: "x 4" },
  { value: 6, label: "x 6" },
  { value: 8, label: "x 8" },
  { value: 12, label: "x 12" },
  { value: 16, label: "x 116" },
  { value: 24, label: "x 124" },
  { value: 32, label: "x 132" },
  { value: 48, label: "x 148" },
  { value: 64, label: "x 164" },
  { value: 96, label: "x 196" },
  { value: 128, label: "x 128" },
  { value: 192, label: "x 192" },
  { value: 256, label: "x 256" },
];

export const BANDS_PER_OCTAVE_VALUES = [
  { value: 12, label: "12" },
  { value: 24, label: "24" },
  { value: 36, label: "36" },
  { value: 48, label: "48" },
  { value: 60, label: "60" },
  { value: 72, label: "72" },
  { value: 84, label: "84" },
  { value: 96, label: "96" },
];

export const BLEND_MODES = [
  { value: 0, label: "Mix" },
  { value: 1, label: "Add" },
  { value: 2, label: "Subtract" },
  { value: 3, label: "Multiply" },
  { value: 4, label: "Divide" },
  { value: 5, label: "Maximum" },
  { value: 6, label: "Minimum" },
  { value: 7, label: "Difference" },
  { value: 8, label: "Dissolve" },
];

export const MODULATOR_MODES = [{ value: 0, label: "Shape" }];

export const PATTERN_SHAPES = [
  { value: 0, label: "Sine" },
  { value: 1, label: "Triangle" },
  { value: 2, label: "Square" },
  { value: 3, label: "Sawtooth" },
  { value: 4, label: "Pulse" },
  { value: 5, label: "Random" },
  { value: 6, label: "Smooth Noise" },
  { value: 7, label: "Cloud Noise" },
  { value: 8, label: "Glass Noise" },
  { value: 9, label: "Ghost Noise" },
  { value: 10, label: "Bubble Noise" },
  { value: 11, label: "Selected Scale" },
];

export const EDGE_MODE = [
  { value: 0, label: "Cut" },
  { value: 1, label: "Bleed" },
  { value: 2, label: "Wrap" },
  { value: 3, label: "Mirror" },
];
