import { pickSectionPresetColor, type SectionPreset } from "./section-presets";

/** A sequencer grid as the modulator stores it. Row 0 is the lowest band. */
const seq = (values: number[][]) => JSON.stringify({ values });

/**
 * Starting points shipped with the app, one list per section. Each preset names
 * only the parameters it cares about; applying one returns every other
 * parameter in that section to its default.
 */
const presets: Omit<SectionPreset, "isFactory" | "color">[] = [
  {
    id: "effect-blur-tail",
    scope: "effect:blur",
    name: "Tail",
    description: "Trails the sound forwards into a reverb tail.",
    values: { blurAmountTime: 100, blurAmountPitch: 0, blurOrigin: 0, blurSamplesX: 32, blurSamplesY: 1 },
  },
  {
    id: "effect-blur-pre-echo",
    scope: "effect:blur",
    name: "Pre-echo",
    description: "Runs the smear backwards, so the sound arrives before it starts.",
    values: { blurAmountTime: 100, blurAmountPitch: 0, blurOrigin: 2, blurSamplesX: 32, blurSamplesY: 1 },
  },
  {
    id: "effect-blur-wash",
    scope: "effect:blur",
    name: "Wash",
    description: "Spreads both ways at once and blends the harmonics into a pad.",
    values: { blurAmountTime: 70, blurAmountPitch: 40, blurOrigin: 1, blurSamplesX: 32, blurSamplesY: 32 },
  },
  {
    id: "effect-blur-grain",
    scope: "effect:blur",
    name: "Grain",
    description: "A rough smear, with every tap scattered.",
    values: {
      blurAmountTime: 60,
      blurAmountPitch: 20,
      blurNoiseTime: 80,
      blurNoisePitch: 60,
      blurOrigin: 1,
      blurSamplesX: 24,
      blurSamplesY: 16,
    },
  },

  {
    id: "effect-dynamics-gate",
    scope: "effect:dynamics",
    name: "Gate",
    description: "Drops everything under the threshold and leaves the peaks standing.",
    values: { dynamicsThresholdDb: -30, dynamicsUpperRatio: 1, dynamicsLowerRatio: 0, dynamicsKnee: 3 },
  },
  {
    id: "effect-dynamics-squash",
    scope: "effect:dynamics",
    name: "Squash",
    description: "Flattens the loud parts towards the quiet ones.",
    values: { dynamicsThresholdDb: -30, dynamicsUpperRatio: 0.3, dynamicsLowerRatio: 1, dynamicsKnee: 12 },
  },
  {
    id: "effect-dynamics-lift-the-tails",
    scope: "effect:dynamics",
    name: "Lift Tails",
    description: "Raises the quiet detail without touching the hits.",
    values: { dynamicsThresholdDb: -40, dynamicsUpperRatio: 1, dynamicsLowerRatio: 2, dynamicsKnee: 18 },
  },
  {
    id: "effect-dynamics-invert",
    scope: "effect:dynamics",
    name: "Invert",
    description: "Turns the quiet parts loud and the loud parts quiet.",
    values: { dynamicsThresholdDb: -30, dynamicsUpperRatio: -1, dynamicsLowerRatio: -1, dynamicsKnee: 12 },
  },
  {
    id: "effect-dynamics-erase",
    scope: "effect:dynamics",
    name: "Erase",
    description: "Takes the level all the way down.",
    values: { dynamicsGainDb: -80 },
  },

  {
    id: "effect-transform-octave-up",
    scope: "effect:transform",
    name: "Octave Up",
    description: "Lifts the sound twelve semitones.",
    values: { transformShiftSemis: 12 },
  },
  {
    id: "effect-transform-octave-down",
    scope: "effect:transform",
    name: "Octave Down",
    description: "Drops the sound twelve semitones.",
    values: { transformShiftSemis: -12 },
  },
  {
    id: "effect-transform-reverse",
    scope: "effect:transform",
    name: "Reverse",
    description: "Plays the sound backwards in place.",
    values: { transformScaleTime: -1 },
  },
  {
    id: "effect-transform-half-speed",
    scope: "effect:transform",
    name: "Half Speed",
    description: "Stretches the sound to twice its length, holding its pitch.",
    values: { transformScaleTime: 2 },
  },
  {
    id: "effect-transform-harmonic-spread",
    scope: "effect:transform",
    name: "Spread",
    description: "Pushes the harmonics apart, thinning a tone into a bell.",
    values: { transformScalePitch: 1.5 },
  },
  {
    id: "effect-transform-tilt",
    scope: "effect:transform",
    name: "Tilt",
    description: "Turns the sound on the canvas, so a sweep leans towards a chord.",
    values: { transformRotation: 30, transformEdgeMode: 1 },
  },

  {
    id: "effect-clone-delay",
    scope: "effect:clone",
    name: "Delay",
    description: "Eight echoes a sixteenth apart, each quieter than the last.",
    values: { cloneSpaceBeats: 0.25, cloneCountX: 8, cloneCountY: 1, cloneDecay: 60, cloneDirectionX: 0 },
  },
  {
    id: "effect-clone-octaves",
    scope: "effect:clone",
    name: "Octaves",
    description: "Stacks octaves above the sound, without letting them cancel.",
    values: {
      cloneSpaceSemis: 12,
      cloneCountX: 1,
      cloneCountY: 3,
      cloneDirectionY: 0,
      cloneDecay: 40,
      cloneSumMode: 1,
    },
  },
  {
    id: "effect-clone-harmonic-series",
    scope: "effect:clone",
    name: "Harmonics",
    description: "Builds a harmonic series on whatever it covers.",
    values: {
      cloneSpaceSemis: 12,
      cloneCountX: 1,
      cloneCountY: 8,
      cloneShapeY: "harmonic",
      cloneDirectionY: 0,
      cloneDecay: 30,
      cloneSumMode: 1,
    },
  },
  {
    id: "effect-clone-bouncing-ball",
    scope: "effect:clone",
    name: "Bouncing Ball",
    description: "Echoes that crowd closer together as they fade, like a ball settling.",
    values: {
      cloneSpaceBeats: 0.5,
      cloneCountX: 8,
      cloneCountY: 1,
      cloneShapeX: "harmonic",
      cloneDirectionX: 0,
      cloneDecay: 70,
    },
  },
  {
    id: "effect-clone-comb",
    scope: "effect:clone",
    name: "Comb",
    description: "Copies close enough together to interfere, hollowing the sound out.",
    values: { cloneSpaceBeats: 0.01, cloneCountX: 16, cloneCountY: 1, cloneDecay: 0, cloneSumMode: 0 },
  },
  {
    id: "effect-clone-struck-bar",
    scope: "effect:clone",
    name: "Struck Bar",
    description: "A stack that runs sharp as it climbs, the way a struck bar does.",
    values: {
      cloneSpaceSemis: 12,
      cloneCountX: 1,
      cloneCountY: 7,
      cloneShapeY: "inharmonic",
      cloneDirectionY: 0,
      cloneDecay: 35,
      cloneSumMode: 1,
    },
  },

  {
    id: "effect-evolve-smear",
    scope: "effect:evolve",
    name: "Smear",
    description: "Bleeds the sound outwards with no current behind it.",
    values: { evolveSpread: 80, evolveFlow: 0, evolveScaleX: 60, evolveScaleY: 20 },
  },
  {
    id: "effect-evolve-erode",
    scope: "effect:evolve",
    name: "Erode",
    description: "Eats the material away, leaving only what was strongest.",
    values: { evolveDecay: 40, evolveSpread: 50, evolveGrow: -20, evolveFlow: 0 },
  },
  {
    id: "effect-evolve-climb",
    scope: "effect:evolve",
    name: "Climb",
    description: "The sound creeps upwards in pitch as it goes.",
    values: { evolveFlow: 40, evolveDriftY: 60, evolveSpread: 30 },
  },
  {
    id: "effect-evolve-bloom",
    scope: "effect:evolve",
    name: "Bloom",
    description: "Feeds the sound back into itself until it takes over.",
    values: { evolveGrow: 70, evolveSpread: 60, evolveDecay: -20, evolveFlow: 0 },
  },
  {
    id: "effect-evolve-swirl",
    scope: "effect:evolve",
    name: "Swirl",
    description: "Smearing with a rotation in it.",
    values: { evolveSwirl: 80, evolveFlow: 50, evolveSpread: 20 },
  },
  {
    id: "effect-evolve-boil",
    scope: "effect:evolve",
    name: "Boil",
    description: "Small-scale churn that never settles.",
    values: { evolveGrow: 50, evolveDecay: 40, evolveSwirl: 40, evolveScaleX: 20, evolveScaleY: 20 },
  },

  {
    id: "effect-binaural-left",
    scope: "effect:binaural",
    name: "Left",
    description: "Hard over to the left.",
    values: { binauralAzimuth: -90, binauralDistance: 1, binauralStereoAngle: 120 },
  },
  {
    id: "effect-binaural-right",
    scope: "effect:binaural",
    name: "Right",
    description: "Hard over to the right.",
    values: { binauralAzimuth: 90, binauralDistance: 1, binauralStereoAngle: 120 },
  },
  {
    id: "effect-binaural-behind",
    scope: "effect:binaural",
    name: "Behind",
    description: "Directly behind the head.",
    values: { binauralAzimuth: 180, binauralDistance: 1.5, binauralStereoAngle: 120 },
  },
  {
    id: "effect-binaural-distant",
    scope: "effect:binaural",
    name: "Distant",
    description: "Far off, and dulled by the air on the way.",
    values: { binauralAzimuth: 0, binauralDistance: 6, binauralStereoAngle: 60 },
  },
  {
    id: "effect-binaural-too-close",
    scope: "effect:binaural",
    name: "Too Close",
    description: "Nearer than anything ought to be.",
    values: { binauralAzimuth: 0, binauralDistance: 0.1, binauralStereoAngle: 180 },
  },

  {
    id: "effect-sort-gather-up",
    scope: "effect:sort",
    name: "Gather Up",
    description: "Collects the loud content towards the top of the brush.",
    values: { sortDirection: 1, sortOrder: 0, sortBy: 0, sortStereoMode: 0 },
  },
  {
    id: "effect-sort-smear-time",
    scope: "effect:sort",
    name: "Smear Time",
    description: "Reorders each band along time, loudest first.",
    values: { sortDirection: 0, sortOrder: 0, sortBy: 2, sortStereoMode: 0 },
  },
  {
    id: "effect-sort-spectral-ramp",
    scope: "effect:sort",
    name: "Spectral Ramp",
    description: "Stacks the bands back up in frequency order.",
    values: { sortDirection: 1, sortOrder: 0, sortBy: 3, sortStereoMode: 0 },
  },
  {
    id: "effect-sort-stereo-tear",
    scope: "effect:sort",
    name: "Stereo Tear",
    description: "Sorts each channel on its own, pulling the image apart.",
    values: { sortDirection: 0, sortOrder: 0, sortBy: 4, sortStereoMode: 1 },
  },
  {
    id: "effect-sort-glitch",
    scope: "effect:sort",
    name: "Glitch",
    description: "Both axes at once, ranked by phase, with the channels loose.",
    values: { sortDirection: 2, sortOrder: 1, sortBy: 1, sortStereoMode: 1 },
  },

  {
    id: "effect-reflow-snap-to-scale",
    scope: "effect:reflow",
    name: "Snap to Scale",
    description: "Pulls every pitch onto the nearest note of the scale.",
    values: { reflowMode: 0, reflowAmount: 100, reflowReach: 12 },
  },
  {
    id: "effect-reflow-nudge",
    scope: "effect:reflow",
    name: "Nudge",
    description: "Light correction, so nothing travels far.",
    values: { reflowMode: 0, reflowAmount: 50, reflowReach: 3 },
  },
  {
    id: "effect-reflow-detune",
    scope: "effect:reflow",
    name: "Detune",
    description: "Pushes pitches away from the scale instead of onto it.",
    values: { reflowMode: 0, reflowAmount: -30, reflowReach: 6 },
  },
  {
    id: "effect-reflow-monotone",
    scope: "effect:reflow",
    name: "Monotone",
    description: "Everything collapses onto a single pitch.",
    values: { reflowMode: 1, reflowAmount: 100, reflowPitch: -12, reflowReach: 48 },
  },
  {
    id: "effect-reflow-spread",
    scope: "effect:reflow",
    name: "Spread",
    description: "Bends the partials apart, thinning a tone into a bell.",
    values: { reflowMode: 2, reflowAmount: 100, reflowStretch: 1.5, reflowPitch: -12, reflowReach: 48 },
  },
  {
    id: "effect-reflow-collapse",
    scope: "effect:reflow",
    name: "Collapse",
    description: "Every partial onto one point.",
    values: { reflowMode: 2, reflowAmount: 100, reflowStretch: 0, reflowPitch: -12, reflowReach: 48 },
  },

  {
    id: "effect-convolve-room",
    scope: "effect:convolve",
    name: "Room",
    description: "A short, close tail.",
    values: { convolveIrSize: 48, convolveIrTimeOffset: 0, convolveIrRate: 1, convolveGainDb: 0 },
  },
  {
    id: "effect-convolve-hall",
    scope: "effect:convolve",
    name: "Hall",
    description: "A long one, with room to decay.",
    values: { convolveIrSize: 256, convolveIrRate: 1, convolveGainDb: -3 },
  },
  {
    id: "effect-convolve-gated",
    scope: "effect:convolve",
    name: "Gated",
    description: "Cut off before it has a chance to decay.",
    values: { convolveIrSize: 24, convolveIrTimeOffset: 0, convolveIrRate: 1, convolveGainDb: 3 },
  },
  {
    id: "effect-convolve-reverse",
    scope: "effect:convolve",
    name: "Reverse",
    description: "The tail runs backwards into the sound.",
    values: { convolveIrSize: 128, convolveIrRate: -1 },
  },
  {
    id: "effect-convolve-stretched",
    scope: "effect:convolve",
    name: "Stretched",
    description: "The tail smeared out to four times its length.",
    values: { convolveIrSize: 256, convolveIrRate: 0.25 },
  },

  {
    id: "modulator-slow-sweep",
    scope: "modulator",
    name: "Slow Sweep",
    description: "One cycle every eight beats, and no change with pitch.",
    values: { Mode: 0, PatternShape: 0, PatternRateBeats: 8, PatternRateSemis: 0 },
  },
  {
    id: "modulator-bar-ramp",
    scope: "modulator",
    name: "Bar Ramp",
    description: "Rises across each bar, then drops back.",
    values: { Mode: 0, PatternShape: 3, PatternRateBeats: 4, PatternRateSemis: 0 },
  },
  {
    id: "modulator-pitch-stripes",
    scope: "modulator",
    name: "Pitch Stripes",
    description: "Varies with pitch alone, one cycle per octave.",
    values: { Mode: 0, PatternShape: 0, PatternRateBeats: 0, PatternRateSemis: 12 },
  },
  {
    id: "modulator-scale-bands",
    scope: "modulator",
    name: "Scale Bands",
    description: "Steps with the notes of the selected scale.",
    values: { Mode: 0, PatternShape: 11, PatternRateBeats: 0, PatternRateSemis: 12 },
  },
  {
    id: "modulator-random-steps",
    scope: "modulator",
    name: "Random Steps",
    description: "Holds a new random value for each beat and each octave.",
    values: { Mode: 0, PatternShape: 5, PatternRateBeats: 1, PatternRateSemis: 12 },
  },
  {
    id: "modulator-clouds",
    scope: "modulator",
    name: "Clouds",
    description: "A soft field drifting over both time and pitch.",
    values: { Mode: 0, PatternShape: 14, PatternRateBeats: 4, PatternRateSemis: 24 },
  },
  {
    id: "modulator-ripples",
    scope: "modulator",
    name: "Ripples",
    description: "Diagonal interference across the canvas.",
    values: { Mode: 0, PatternShape: 18, PatternRateBeats: 2, PatternRateSemis: 24, Rotation: 45 },
  },
  {
    id: "modulator-marble",
    scope: "modulator",
    name: "Marble",
    description: "Veined texture, slow across the whole file.",
    values: { Mode: 0, PatternShape: 22, PatternRateBeats: 8, PatternRateSemis: 36 },
  },
  {
    id: "modulator-follow-loudness",
    scope: "modulator",
    name: "Follow Loudness",
    description: "Tracks the material's own level.",
    values: { Mode: 1, EnvelopeSource: 0, EnvelopeSmoothingBeats: 0.25, EnvelopeMinDb: -60, EnvelopeMaxDb: 0 },
  },
  {
    id: "modulator-follow-panning",
    scope: "modulator",
    name: "Follow Panning",
    description: "Tracks where the material sits in the stereo image.",
    values: { Mode: 1, EnvelopeSource: 2, EnvelopeSmoothingBeats: 0.5 },
  },

  {
    id: "modulator-four-on-the-floor",
    scope: "modulator",
    name: "Four on the Floor",
    description: "A hit on every beat of the bar.",
    values: {
      Mode: 2,
      SeqStepsX: 8,
      SeqStepsY: 1,
      SeqLoopBeats: 4,
      SeqData: seq([[1, 0, 1, 0, 1, 0, 1, 0]]),
    },
  },
  {
    id: "modulator-offbeat",
    scope: "modulator",
    name: "Offbeat",
    description: "The beats the last one leaves out.",
    values: {
      Mode: 2,
      SeqStepsX: 8,
      SeqStepsY: 1,
      SeqLoopBeats: 4,
      SeqData: seq([[0, 1, 0, 1, 0, 1, 0, 1]]),
    },
  },
  {
    id: "modulator-euclid-3-8",
    scope: "modulator",
    name: "Euclid 3/8",
    description: "Three hits spread over eight steps.",
    values: {
      Mode: 2,
      SeqStepsX: 8,
      SeqStepsY: 1,
      SeqLoopBeats: 4,
      SeqData: seq([[1, 0, 0, 1, 0, 0, 1, 0]]),
    },
  },
  {
    id: "modulator-swung-eighths",
    scope: "modulator",
    name: "Swung Eighths",
    description: "Eighths with the offbeats softened and pushed late.",
    values: {
      Mode: 2,
      SeqStepsX: 8,
      SeqStepsY: 1,
      SeqLoopBeats: 4,
      SeqSwing: 60,
      SeqData: seq([[1, 0.55, 1, 0.55, 1, 0.55, 1, 0.55]]),
    },
  },
  {
    id: "modulator-breathe",
    scope: "modulator",
    name: "Breathe",
    description: "Swells in and back out across the bar.",
    values: {
      Mode: 2,
      SeqStepsX: 16,
      SeqStepsY: 1,
      SeqLoopBeats: 4,
      SeqData: seq([[0.13, 0.25, 0.38, 0.5, 0.63, 0.75, 0.88, 1, 1, 0.88, 0.75, 0.63, 0.5, 0.38, 0.25, 0.13]]),
    },
  },
  {
    id: "modulator-decay-hits",
    scope: "modulator",
    name: "Decay Hits",
    description: "Each hit falls away instead of holding.",
    values: {
      Mode: 2,
      SeqStepsX: 8,
      SeqStepsY: 1,
      SeqLoopBeats: 4,
      SeqData: seq([[1, 0.5, 0.2, 0, 1, 0.5, 0.2, 0]]),
    },
  },
  {
    id: "modulator-checkerboard",
    scope: "modulator",
    name: "Checkerboard",
    description: "Neighbouring bands get opposite halves of the rhythm.",
    values: {
      Mode: 2,
      SeqStepsX: 8,
      SeqStepsY: 4,
      SeqLoopBeats: 4,
      SeqLoopSemis: 24,
      SeqData: seq([
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
      ]),
    },
  },
  {
    id: "modulator-staircase",
    scope: "modulator",
    name: "Staircase",
    description: "The modulation climbs the spectrum as the bar runs.",
    values: {
      Mode: 2,
      SeqStepsX: 8,
      SeqStepsY: 4,
      SeqLoopBeats: 4,
      SeqLoopSemis: 24,
      SeqData: seq([
        [1, 0, 0, 0, 1, 0, 0, 0],
        [0, 1, 0, 0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0, 0, 1, 0],
        [0, 0, 0, 1, 0, 0, 0, 1],
      ]),
    },
  },
  {
    id: "modulator-pitch-comb",
    scope: "modulator",
    name: "Pitch Comb",
    description: "Stripes up the spectrum that never change with time.",
    values: {
      Mode: 2,
      SeqStepsX: 1,
      SeqStepsY: 8,
      SeqLoopSemis: 24,
      SeqData: seq([[1], [0], [1], [0], [1], [0], [1], [0]]),
    },
  },
  {
    id: "modulator-scatter",
    scope: "modulator",
    name: "Scatter",
    description: "A different value in every band and every step.",
    values: {
      Mode: 2,
      SeqStepsX: 16,
      SeqStepsY: 8,
      SeqLoopBeats: 8,
      SeqLoopSemis: 48,
      SeqData: seq([
        [0.31, 0.64, 0.62, 0.91, 0.73, 0.34, 0.19, 0.45, 0.1, 0.44, 0.52, 0.49, 0.19, 0.26, 0.82, 0.17],
        [0.75, 0.88, 0.42, 0.35, 0.17, 0.92, 0.83, 0.89, 0.78, 0.27, 0.91, 0.12, 0.78, 0.05, 0.98, 0.34],
        [0.01, 0.33, 0.04, 0.17, 0.64, 0.5, 0.95, 0.37, 0.3, 0.04, 0.54, 0.48, 0.59, 0.71, 0.19, 0.55],
        [0.49, 0.7, 0.53, 0.2, 0.48, 0.53, 0.4, 0.09, 0.93, 0.26, 0.02, 0.67, 0.8, 1, 0.85, 0.06],
        [0.43, 0.83, 0.97, 0.73, 0.22, 0.66, 0.22, 0.72, 0.35, 0.58, 0.74, 0.61, 0.18, 0.9, 0.76, 0.12],
        [0.17, 0.58, 0.7, 0.69, 0.66, 0.04, 0.93, 0.44, 0.06, 0.15, 0.44, 0.27, 0.56, 0.73, 0.23, 0.15],
        [0.13, 0.89, 0.73, 0.52, 0.65, 0.69, 0.28, 0.44, 0.99, 0.25, 0.59, 0.1, 0.8, 0.65, 0.06, 0.97],
        [0.94, 0.05, 0.25, 0.98, 0.74, 0.26, 0.12, 0.41, 0.51, 0.63, 0.57, 0.81, 0.58, 0.06, 0.07, 0.19],
      ]),
    },
  },
];

/**
 * Colours are assigned by the same rule a saved preset gets one, so a section's
 * list stays spread across the palette however many are added to it.
 */
export const factorySectionPresets: SectionPreset[] = presets.reduce<SectionPreset[]>((assigned, preset) => {
  assigned.push({ ...preset, isFactory: true, color: pickSectionPresetColor(assigned, preset.scope) });
  return assigned;
}, []);
