import { BEAT_VALUES, PITCH_VALUES_NO_FRACTIONS, WRAP_MODES } from "../lib/constants";
import type { BrushState, ZustandSet } from "./types";
import { createParameter } from "./utils";

export const createBrushSlice = (set: ZustandSet): BrushState => ({
  ...createParameter(
    set,
    "brushIntensity",
    {
      name: "Brush Strength",
      label: "Strength",
      description: "Controls the strength of the brush.",
      value: 100,
      min: 0,
      max: 100,
      step: 1,
      unit: "%",
    },
    true,
  ),
  ...createParameter(
    set,
    "brushIterations",
    {
      name: "Brush Iterations",
      label: "Iterations",
      description: "How many times to apply the brush effect.",
      value: 1,
      min: 1,
      max: 20,
      step: 1,
    },
    false,
  ),
  ...createParameter(
    set,
    "brushPan",
    {
      name: "Pan",
      label: "Pan",
      description: "Pans the brush effect left or right.",
      value: 0.0,
      min: -100,
      max: 100,
      step: 1,
      unit: "%",
    },
    true,
  ),
  ...createParameter(
    set,
    "brushFeatherTime",
    {
      name: "Feather Time",
      label: "Feather H",
      description: "Softens the brush effect at the edges of the time selection.",
      value: 0,
      min: 0,
      max: 100,
      step: 1,
      unit: "%",
    },
    false,
  ),
  ...createParameter(
    set,
    "brushFeatherPitch",
    {
      name: "Feather Pitch",
      label: "Feather V",
      description: "Softens the brush effect at the edges of the pitch selection.",
      value: 0,
      min: 0,
      max: 100,
      step: 1,
      unit: "%",
    },
    false,
  ),
  ...createParameter(
    set,
    "brushFeatherSlopeTime",
    {
      name: "Feather Slope Time",
      label: "Slope H",
      description:
        "Controls the slope of the time feathering. -100 is fast initial rise, long tail, 100 is slow attack, fast finish.",
      value: 0,
      min: -100,
      max: 100,
      step: 1,
      unit: "%",
    },
    false,
  ),
  ...createParameter(
    set,
    "brushFeatherSlopePitch",
    {
      name: "Feather Slope Pitch",
      label: "Slope V",
      description:
        "Controls the slope of the pitch feathering. -100 is fast initial rise, long tail, 100 is slow attack, fast finish.",
      value: 0,
      min: -100,
      max: 100,
      step: 1,
      unit: "%",
    },
    false,
  ),
  sourcePosition: null,
  setSourcePosition: (position: { beats: number; pitch: number; fileId: string } | null) =>
    set({ sourcePosition: position, lockedOffset: null }),
  ...createParameter(
    set,
    "sourcePositionMode",
    {
      name: "Source Position Mode",
      label: "Mode",
      description: "How the source position is used when painting.",
      value: "anchored" as string,
      options: [
        { value: "fixed", label: "Fixed" },
        { value: "anchored", label: "Anchored" },
        { value: "offset", label: "Offset" },
      ],
    },
    false,
  ),
  isSettingPosition: false,
  setIsSettingPosition: (value: boolean) => set({ isSettingPosition: value }),
  brushStartPosition: null,
  setBrushStartPosition: (position: { beats: number; pitch: number } | null) => set({ brushStartPosition: position }),
  lockedOffset: null,
  setLockedOffset: (offset: { beats: number; pitch: number } | null) => set({ lockedOffset: offset }),
  ...createParameter(
    set,
    "brushWidthBeats",
    {
      name: "Brush Width",
      label: "Width",
      description: "The width of the brush in beats.",
      value: 1,
      values: [...BEAT_VALUES, { value: 0, label: "Full" }].map((value) => ({
        value: value.value,
        label: value.label,
      })),
    },
    false,
  ),
  ...createParameter(
    set,
    "brushHeightSemis",
    {
      name: "Brush Height",
      label: "Height",
      description: "The height of the brush in semitones.",
      value: 12,
      values: [...PITCH_VALUES_NO_FRACTIONS, { value: 0, label: "Full" }].map((value) => ({
        value: value.value,
        label: value.label,
      })),
    },
    false,
  ),
  ...createParameter(
    set,
    "brushSizeLockedToGrid",
    {
      name: "Lock Brush Size to Grid",
      label: "Lock size",
      description: "Locks the brush size to the grid size.",
      value: false as boolean,
    },
    false,
  ),
  ...createParameter(
    set,
    "brushWrapMode",
    {
      name: "Wrap Mode",
      label: "Wrap",
      description: "Controls whether the brush wraps around the edges of the canvas.",
      value: 0,
      options: WRAP_MODES,
    },
    false,
  ),
});
